/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as MyDomainsRouteImport } from './routes/my-domains'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as DomainDomainRouteImport } from './routes/domain.$domain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDomainsRoute = MyDomainsRouteImport.update({
  id: '/my-domains',
  path: '/my-domains',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainDomainRoute = DomainDomainRouteImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auctions': typeof AuctionsRoute
  '/autopilot': typeof AutopilotRoute
  '/discover': typeof DiscoverRoute
  '/insights': typeof InsightsRoute
  '/listings': typeof ListingsRoute
  '/my-domains': typeof MyDomainsRoute
  '/offers': typeof OffersRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/domain/$domain': typeof DomainDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auctions': typeof AuctionsRoute
  '/autopilot': typeof AutopilotRoute
  '/discover': typeof DiscoverRoute
  '/insights': typeof InsightsRoute
  '/listings': typeof ListingsRoute
  '/my-domains': typeof MyDomainsRoute
  '/offers': typeof OffersRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/domain/$domain': typeof DomainDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auctions': typeof AuctionsRoute
  '/autopilot': typeof AutopilotRoute
  '/discover': typeof DiscoverRoute
  '/insights': typeof InsightsRoute
  '/listings': typeof ListingsRoute
  '/my-domains': typeof MyDomainsRoute
  '/offers': typeof OffersRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/watchlist': typeof WatchlistRoute
  '/domain/$domain': typeof DomainDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auctions'
    | '/autopilot'
    | '/discover'
    | '/insights'
    | '/listings'
    | '/my-domains'
    | '/offers'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/watchlist'
    | '/domain/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auctions'
    | '/autopilot'
    | '/discover'
    | '/insights'
    | '/listings'
    | '/my-domains'
    | '/offers'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/watchlist'
    | '/domain/$domain'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auctions'
    | '/autopilot'
    | '/discover'
    | '/insights'
    | '/listings'
    | '/my-domains'
    | '/offers'
    | '/settings'
    | '/transactions'
    | '/wallet'
    | '/watchlist'
    | '/domain/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuctionsRoute: typeof AuctionsRoute
  AutopilotRoute: typeof AutopilotRoute
  DiscoverRoute: typeof DiscoverRoute
  InsightsRoute: typeof InsightsRoute
  ListingsRoute: typeof ListingsRoute
  MyDomainsRoute: typeof MyDomainsRoute
  OffersRoute: typeof OffersRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletRoute: typeof WalletRoute
  WatchlistRoute: typeof WatchlistRoute
  DomainDomainRoute: typeof DomainDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-domains': {
      id: '/my-domains'
      path: '/my-domains'
      fullPath: '/my-domains'
      preLoaderRoute: typeof MyDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuctionsRoute: AuctionsRoute,
  AutopilotRoute: AutopilotRoute,
  DiscoverRoute: DiscoverRoute,
  InsightsRoute: InsightsRoute,
  ListingsRoute: ListingsRoute,
  MyDomainsRoute: MyDomainsRoute,
  OffersRoute: OffersRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  WalletRoute: WalletRoute,
  WatchlistRoute: WatchlistRoute,
  DomainDomainRoute: DomainDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
