/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as MyDomainsRouteImport } from './routes/my-domains'
import { Route as DomainDomainRouteImport } from './routes/domain.$domain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDomainsRoute = MyDomainsRouteImport.update({
  id: '/my-domains',
  path: '/my-domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainDomainRoute = DomainDomainRouteImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/discover': typeof DiscoverRoute
  '/my-domains': typeof MyDomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/discover': typeof DiscoverRoute
  '/my-domains': typeof MyDomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/discover': typeof DiscoverRoute
  '/my-domains': typeof MyDomainsRoute
  '/domain/$domain': typeof DomainDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auctions' | '/discover' | '/my-domains' | '/domain/$domain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auctions' | '/discover' | '/my-domains' | '/domain/$domain'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/discover'
    | '/my-domains'
    | '/domain/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  DiscoverRoute: typeof DiscoverRoute
  MyDomainsRoute: typeof MyDomainsRoute
  DomainDomainRoute: typeof DomainDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-domains': {
      id: '/my-domains'
      path: '/my-domains'
      fullPath: '/my-domains'
      preLoaderRoute: typeof MyDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  DiscoverRoute: DiscoverRoute,
  MyDomainsRoute: MyDomainsRoute,
  DomainDomainRoute: DomainDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
